# Generated by Django 5.2 on 2025-05-13 09:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Location', '0001_initial'),
        ('Package', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='package_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='Package.package'),
        ),
    ]
