# Generated by Django 5.2 on 2025-05-30 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Location', '0003_remove_location_city_remove_location_country_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='package_id',
            new_name='package',
        ),
    ]
