# Generated by Django 5.2 on 2025-05-17 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Delivery', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='delivery',
            old_name='courier_id',
            new_name='courier',
        ),
    ]
