# Generated by Django 5.2 on 2025-05-17 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Delivery', '0003_rename_courier_id_delivery_courier'),
    ]

    operations = [
        migrations.RenameField(
            model_name='delivery',
            old_name='package_id',
            new_name='package',
        ),
    ]
