# Generated by Django 5.2 on 2025-05-22 12:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Courier', '0001_initial'),
        ('Delivery', '0004_rename_package_id_delivery_package'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='courier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='Courier.courier'),
        ),
    ]
