# Generated by Django 5.2 on 2025-05-25 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Delivery', '0005_alter_delivery_courier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='delivery_time',
            field=models.CharField(max_length=40),
        ),
    ]
