# Generated by Django 5.2 on 2025-05-25 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Delivery', '0006_alter_delivery_delivery_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='delivery_time',
            field=models.DateTimeField(max_length=40),
        ),
    ]
