# Generated by Django 5.2 on 2025-05-30 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Delivery', '0007_alter_delivery_delivery_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='delivery_type',
            field=models.CharField(choices=[('domestic', 'Domestic'), ('international', 'International')], default='domestic', max_length=50),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='pickup_time',
            field=models.DateTimeField(max_length=40),
        ),
    ]
