# Generated by Django 5.2 on 2025-05-30 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Delivery', '0008_delivery_delivery_type_alter_delivery_pickup_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='pickup_time',
            field=models.DateTimeField(max_length=50),
        ),
    ]
