# Generated by Django 5.2 on 2025-05-30 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Delivery', '0010_alter_delivery_pickup_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='pickup_time',
            field=models.DateTimeField(blank=True, max_length=50, null=True),
        ),
    ]
