# Generated by Django 5.2 on 2025-06-02 09:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Delivery', '0011_alter_delivery_pickup_time'),
        ('Package', '0006_remove_package_senders_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='Package.package'),
        ),
    ]
