# Generated by Django 5.2 on 2025-06-06 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Delivery', '0012_alter_delivery_package'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delivery',
            name='delivery_status',
        ),
        migrations.RemoveField(
            model_name='delivery',
            name='delivery_time',
        ),
        migrations.RemoveField(
            model_name='delivery',
            name='pickup_time',
        ),
        migrations.AddField(
            model_name='delivery',
            name='current_status',
            field=models.CharField(default='created', max_length=50),
        ),
        migrations.AddField(
            model_name='delivery',
            name='estimated_delivery_date',
            field=models.DateField(blank=True, max_length=40, null=True),
        ),
    ]
