# Generated by Django 5.2 on 2025-06-06 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Delivery', '0013_remove_delivery_delivery_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='estimated_delivery_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
