# Generated by Django 5.2 on 2025-06-06 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Delivery', '0014_alter_delivery_estimated_delivery_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='current_status',
            field=models.CharField(choices=[('created', 'Created'), ('on_transit', 'On Transit'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='created', max_length=50),
        ),
    ]
