# Generated by Django 5.2 on 2025-06-06 06:17

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Delivery', '0013_remove_delivery_delivery_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('created', 'Created'), ('in_transit', 'In Transit'), ('arrived', 'Arrived'), ('delivered', 'Delivered')], max_length=50)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('delivery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='histories', to='Delivery.delivery')),
            ],
        ),
    ]
