# Generated by Django 5.2 on 2025-05-15 05:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Package', '0003_remove_package_dimensions_package_height_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='pickup_date',
            field=models.DateField(default=datetime.datetime.now, max_length=50),
        ),
        migrations.AddField(
            model_name='package',
            name='senders_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='package',
            name='width',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='package',
            name='description',
            field=models.TextField(blank=True, max_length=225, null=True),
        ),
    ]
