# Generated by Django 5.2 on 2025-05-19 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Package', '0004_package_pickup_date_package_senders_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='package',
            old_name='sender_id',
            new_name='user',
        ),
    ]
