# Generated by Django 5.2 on 2025-05-19 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Package', '0005_rename_sender_id_package_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='senders_name',
        ),
    ]
