# Generated by Django 5.2 on 2025-05-23 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Receipt', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='receipt',
            old_name='package_id',
            new_name='package',
        ),
        migrations.AlterField(
            model_name='receipt',
            name='payment_status',
            field=models.BooleanField(choices=[('pending', 'Pending'), ('paid', 'Paid')], default='paid', max_length=20),
        ),
    ]
