# Generated by Django 5.2 on 2025-05-23 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Receipt', '0002_rename_package_id_receipt_package_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid')], default='paid', max_length=20),
        ),
    ]
