# Generated by Django 5.2 on 2025-05-22 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('courier', 'Courier'), ('user', 'User')], default='user', max_length=20),
        ),
    ]
